MODEL:
  META_ARCHITECTURE: "YolactBackboneWithFPN"
  BACKBONE:
    NAME: "build_resnet26d_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.002
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  DEFAULT_WARMUP_LR: 0.0001
  WARMUP_FACTOR: 0.1