MODEL:
  META_ARCHITECTURE: "YolactBackboneWithFPN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  FPN:
    LASTLEVEL: "LastLevelP6P7"
    FPN_NO_256: 1
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_minival",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 0
SOLVER:
  BASE_LR: 0.002
  WARMUP_ITERS: 1000
  DEFAULT_WARMUP_LR: 0.0001
  WEIGHT_DECAY: 0.0005
  WARMUP_FACTOR: 0.1
  STEPS: (140000, 300000, 350000, 375000) #(280000, 600000, 700000, 750000)
  MAX_ITER: 400000 #800000
  IMS_PER_BATCH : 16
