MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  META_ARCHITECTURE: "YolactBackboneWithFPN"
  BACKBONE:
    NAME: "build_resnet26d_fpn_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  STEPS: (280000, 360000, 400000)
  MAX_ITER: 600000
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)